# Generated by Django 3.2.5 on 2022-10-08 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProject',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('Corporate', 'Corporate'), ('E-Commerse', 'E-Commerse'), ('Blog', 'Blog'), ('Portfolio', 'Portfolio'), ('Wiki', 'Wiki')], max_length=15)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('homePage', models.BooleanField(default=False)),
                ('aboutPage', models.BooleanField(default=False)),
                ('contactPage', models.BooleanField(default=False)),
                ('customPage', models.BooleanField(default=False)),
                ('colorScheme', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
