# Generated by Django 3.2.5 on 2022-10-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_auto_20221009_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproject',
            name='colorScheme',
            field=models.TextField(blank=True, null=True),
        ),
    ]
