# Generated by Django 3.2.5 on 2022-10-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0005_alter_aiproject_custompagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aiproject',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
