# Generated by Django 4.1.2 on 2022-11-07 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0006_auto_20221009_2001"),
    ]

    operations = [
        migrations.RemoveField(model_name="aiproject", name="colorScheme",),
    ]
