# Generated by Django 4.1.2 on 2022-11-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0007_remove_aiproject_colorscheme"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiproject",
            name="projectType",
            field=models.CharField(
                choices=[("Text", "Text"), ("Image", "Image")],
                default="Text",
                max_length=15,
            ),
        ),
    ]
