# Generated by Django 4.1.2 on 2022-11-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0008_aiproject_projecttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproject',
            name='projectType',
            field=models.CharField(choices=[('Text', 'Text'), ('Image', 'Image')], max_length=15),
        ),
    ]
