# Generated by Django 4.1.2 on 2022-10-31 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("custom", "0006_auto_20221009_2001"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pageType",
                    models.CharField(
                        choices=[
                            ("Home", "Home"),
                            ("About", "About"),
                            ("Contact", "Contact"),
                            ("Custom", "Custom"),
                        ],
                        max_length=15,
                    ),
                ),
                ("heading", models.BooleanField()),
                ("navbar", models.BooleanField()),
                ("textbox", models.BooleanField()),
                ("paragraph", models.BooleanField()),
                ("image", models.BooleanField()),
                ("button", models.BooleanField()),
                ("checkbox", models.BooleanField()),
                ("dropdown", models.BooleanField()),
                ("footer", models.BooleanField()),
                ("label", models.BooleanField()),
                ("textarea", models.BooleanField()),
                ("link", models.BooleanField()),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custom.aiproject",
                    ),
                ),
            ],
        ),
    ]
