# Generated by Django 4.1.2 on 2022-11-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textInput", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="textpage",
            name="colorScheme",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="textpage", name="button", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="textpage", name="checkbox", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="textpage", name="dropdown", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="textpage", name="footer", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="textpage", name="heading", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="textpage", name="image", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="textpage", name="label", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="textpage", name="link", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="textpage", name="navbar", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="textpage", name="paragraph", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="textpage", name="textarea", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="textpage", name="textbox", field=models.IntegerField(),
        ),
    ]
