# Generated by Django 4.1.2 on 2022-11-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textInput", "0002_textpage_colorscheme_alter_textpage_button_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textpage",
            name="button",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="textpage",
            name="checkbox",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="textpage",
            name="dropdown",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="textpage",
            name="footer",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="textpage",
            name="heading",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="textpage",
            name="image",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="textpage",
            name="label",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="textpage",
            name="link",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="textpage",
            name="navbar",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="textpage",
            name="paragraph",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="textpage",
            name="textarea",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="textpage",
            name="textbox",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
