# Generated by Django 4.1.2 on 2022-11-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textInput", "0003_alter_textpage_button_alter_textpage_checkbox_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="textpage",
            name="pageName",
            field=models.CharField(default="Custom", max_length=25),
        ),
    ]
