# Generated by Django 4.1.2 on 2022-11-22 08:06

from django.db import migrations, models
import django.db.models.deletion
import textInput.models


class Migration(migrations.Migration):

    dependencies = [
        ('textInput', '0004_textpage_pagename'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='default.jpg', upload_to=textInput.models.get_upload_path)),
                ('textpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textInput.textpage')),
            ],
        ),
    ]
