# Generated by Django 4.1.2 on 2022-11-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textInput", "0005_textpageimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="textpage",
            name="fileName",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
