# Generated by Django 3.2.16 on 2022-11-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInput', '0007_remove_textpage_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpage',
            name='made',
            field=models.BooleanField(default=False),
        ),
    ]
