# Generated by Django 3.2.16 on 2022-11-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageInput', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepage',
            name='made',
            field=models.BooleanField(default=False),
        ),
    ]
